### ISSUE TITLE
What I learned creating a Vue 3 component library

### ISSUE THREAD

**Issue by ElisePatrikainen** [Vue-js-Paris/talks#1]
### Description

All I had to do to make my lib usable:
Vue 3 /Nuxt 3 problems, Storybook & documentation, Vite/rollup config, A11y, Vitest & VTL, Cypress CT, husky, semantic release/conventional commits, netlify, create-my-lib npm package, VS Code settings

### Talk Duration

20 minutes

### Your First and Last Name

Stanislas Ormières

### Your Email

stan@stormier.ninja

### One-line Introduction

Currently, I work as a Senior Front-end Engineer at Berlin’s best tech startup, Contiamo.

### Twitter

https://x.com/laruiss?lang=fr

### GitHub

@laruiss

**Comment by posva** [comment]
test pour assigner @laruiss (désolé du ping, tu peux unsub de l'issue).

Edit: ça n'a pas marché, il faut que la personne concernée participe dans la conversation
